"""add sync fields

Revision ID: a76a8140ad85
Revises: 
Create Date: 2026-01-11 20:44:25.280504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76a8140ad85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('health_sessions')
        batch_op.drop_column('antenatal_followups')
        batch_op.drop_column('referrals_made')
        batch_op.drop_column('immunizations_given')
        batch_op.drop_column('postnatal_followups')

    with op.batch_alter_table('elderly_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('blood_sugar',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('general_patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pregnant_woman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnant_woman', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('is_synced')

    with op.batch_alter_table('general_patient', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('is_synced')

    with op.batch_alter_table('elderly_person', schema=None) as batch_op:
        batch_op.alter_column('blood_sugar',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('is_synced')

    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postnatal_followups', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('immunizations_given', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('referrals_made', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('antenatal_followups', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('health_sessions', sa.INTEGER(), nullable=True))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('is_synced')

    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('is_synced')

    # ### end Alembic commands ###
