"""update asha and patient

Revision ID: 0ea182d64c21
Revises: 23729df0b6fb
Create Date: 2026-01-12 12:50:40.763648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea182d64c21'
down_revision = '23729df0b6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))
        batch_op.drop_column('asha_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asha_phone', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('area')

    # ### end Alembic commands ###
