"""update model

Revision ID: 1495a8e789bc
Revises: efdea1d48ce5
Create Date: 2026-02-14 03:09:23.618336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1495a8e789bc'
down_revision = 'efdea1d48ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anc_visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anc_visit_pregnancy_id'), ['pregnancy_id'], unique=False)

    with op.batch_alter_table('asha_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asha_profile_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_asha_profile_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('case_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_record_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('child_immunization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_immunization_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_immunization_vaccine_schedule_id'), ['vaccine_schedule_id'], unique=False)

    with op.batch_alter_table('child_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_profile_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('elderly_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elderly_profile_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_visit_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('info_video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_info_video_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('medicine_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_reminder_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_profile_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_profile_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_household_id'), ['household_id'], unique=False)

    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pregnancy_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pregnancy_status'), ['status'], unique=False)

    with op.batch_alter_table('supply_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_request_asha_id'), ['asha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_request_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)

    with op.batch_alter_table('vaccine_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccine_schedule_vaccine_id'), ['vaccine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccine_schedule_vaccine_id'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_person_id'))

    with op.batch_alter_table('supply_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_request_patient_id'))
        batch_op.drop_index(batch_op.f('ix_supply_request_asha_id'))

    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pregnancy_status'))
        batch_op.drop_index(batch_op.f('ix_pregnancy_person_id'))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_household_id'))
        batch_op.drop_index(batch_op.f('ix_person_category'))

    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_patient_profile_area'))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_message_is_read'))

    with op.batch_alter_table('medicine_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_reminder_patient_id'))

    with op.batch_alter_table('info_video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_info_video_created_by'))

    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_visit_person_id'))

    with op.batch_alter_table('elderly_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elderly_profile_person_id'))

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_user_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_role'))

    with op.batch_alter_table('child_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_profile_person_id'))

    with op.batch_alter_table('child_immunization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_immunization_vaccine_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_child_immunization_child_id'))

    with op.batch_alter_table('case_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_record_person_id'))

    with op.batch_alter_table('asha_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asha_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_asha_profile_area'))

    with op.batch_alter_table('anc_visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anc_visit_pregnancy_id'))

    # ### end Alembic commands ###
