"""add asha models

Revision ID: 23729df0b6fb
Revises: 9a863ef5bf77
Create Date: 2026-01-12 03:00:45.465688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23729df0b6fb'
down_revision = '9a863ef5bf77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=120), nullable=True),
    sa.Column('birth_weight', sa.Float(), nullable=True),
    sa.Column('mother_name', sa.String(length=120), nullable=True),
    sa.Column('bcg_date', sa.Date(), nullable=True),
    sa.Column('opv_date', sa.Date(), nullable=True),
    sa.Column('pentavalent_date', sa.Date(), nullable=True),
    sa.Column('measles_date', sa.Date(), nullable=True),
    sa.Column('growth_notes', sa.Text(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('households_visited', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('work_pending', sa.Text(), nullable=True),
    sa.Column('work_done', sa.Text(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elderly_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('bp_sys', sa.Integer(), nullable=True),
    sa.Column('bp_dia', sa.Integer(), nullable=True),
    sa.Column('sugar_fasting', sa.Float(), nullable=True),
    sa.Column('sugar_random', sa.Float(), nullable=True),
    sa.Column('blood_sugar', sa.Float(), nullable=True),
    sa.Column('illnesses', sa.Text(), nullable=True),
    sa.Column('medicines', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('referral_facility', sa.String(length=120), nullable=True),
    sa.Column('referral_date', sa.Date(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnant_woman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('lmp_date', sa.Date(), nullable=True),
    sa.Column('edd_date', sa.Date(), nullable=True),
    sa.Column('bp', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('hb', sa.Float(), nullable=True),
    sa.Column('tt_status', sa.String(length=50), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pregnant_woman')
    op.drop_table('patient_register')
    op.drop_table('general_patient')
    op.drop_table('elderly_person')
    op.drop_table('daily_task')
    op.drop_table('child')
    # ### end Alembic commands ###
