"""update model

Revision ID: 3060dffe7a71
Revises: e9723f6e2078
Create Date: 2026-02-24 21:56:51.117424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3060dffe7a71'
down_revision = 'e9723f6e2078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_profile', schema=None) as batch_op:
        batch_op.drop_column('place_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_of_birth', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
