"""attach_asha_id_columns

Revision ID: 4d3c8dda8c30
Revises: 1495a8e789bc
Create Date: 2026-02-14 14:31:10.533591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3c8dda8c30'
down_revision = '1495a8e789bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asha_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_case_record_asha_id'), ['asha_id'], unique=False)
        batch_op.create_foreign_key('fk_case_record_asha_id_user', 'user', ['asha_id'], ['id'])

    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asha_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_health_visit_asha_id'), ['asha_id'], unique=False)
        batch_op.create_foreign_key('fk_health_visit_asha_id_user', 'user', ['asha_id'], ['id'])

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asha_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_household_asha_id'), ['asha_id'], unique=False)
        batch_op.create_foreign_key('fk_household_asha_id_user', 'user', ['asha_id'], ['id'])

    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asha_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pregnancy_asha_id'), ['asha_id'], unique=False)
        batch_op.create_foreign_key('fk_pregnancy_asha_id_user', 'user', ['asha_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asha_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_asha_id'), ['asha_id'], unique=False)
        batch_op.create_foreign_key('fk_task_asha_id_user', 'user', ['asha_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_asha_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_asha_id'))
        batch_op.drop_column('asha_id')

    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pregnancy_asha_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pregnancy_asha_id'))
        batch_op.drop_column('asha_id')

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_constraint('fk_household_asha_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_household_asha_id'))
        batch_op.drop_column('asha_id')

    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_health_visit_asha_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_health_visit_asha_id'))
        batch_op.drop_column('asha_id')

    with op.batch_alter_table('case_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_case_record_asha_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_case_record_asha_id'))
        batch_op.drop_column('asha_id')

    # ### end Alembic commands ###
