"""remove patientregister

Revision ID: 534388a7670c
Revises: 0ea182d64c21
Create Date: 2026-01-20 14:15:22.588492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534388a7670c'
down_revision = '0ea182d64c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_register')
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))

    op.create_table('patient_register',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('phone_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=250), nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
