"""update model

Revision ID: 71657e5eee5c
Revises: 3060dffe7a71
Create Date: 2026-02-24 23:58:03.147248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71657e5eee5c'
down_revision = '3060dffe7a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.drop_column('height')

    # ### end Alembic commands ###
