"""update asha manage

Revision ID: 88bd9a910c97
Revises: aadfc7d9dce4
Create Date: 2026-02-11 23:15:02.050030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bd9a910c97'
down_revision = 'aadfc7d9dce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head_name', sa.String(length=120), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('referral_facility', sa.String(length=120), nullable=True),
    sa.Column('referral_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_weight', sa.Float(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elderly_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('bp_sys', sa.Integer(), nullable=True),
    sa.Column('bp_dia', sa.Integer(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('lmp_date', sa.Date(), nullable=True),
    sa.Column('edd_date', sa.Date(), nullable=True),
    sa.Column('gravida', sa.Integer(), nullable=True),
    sa.Column('para', sa.Integer(), nullable=True),
    sa.Column('high_risk', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anc_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('bp', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('hb', sa.Float(), nullable=True),
    sa.Column('tt_given', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('immunization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('vaccine_name', sa.String(length=50), nullable=True),
    sa.Column('dose_number', sa.Integer(), nullable=True),
    sa.Column('date_given', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('elderly_person')
    op.drop_table('general_patient')
    op.drop_table('daily_task')
    op.drop_table('child')
    op.drop_table('pregnant_woman')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pregnant_woman',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('village', sa.VARCHAR(length=120), nullable=True),
    sa.Column('lmp_date', sa.DATE(), nullable=True),
    sa.Column('edd_date', sa.DATE(), nullable=True),
    sa.Column('bp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('hb', sa.FLOAT(), nullable=True),
    sa.Column('tt_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('follow_up_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('age_years', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=10), nullable=True),
    sa.Column('village', sa.VARCHAR(length=120), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('place_of_birth', sa.VARCHAR(length=120), nullable=True),
    sa.Column('birth_weight', sa.FLOAT(), nullable=True),
    sa.Column('mother_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('bcg_date', sa.DATE(), nullable=True),
    sa.Column('opv_date', sa.DATE(), nullable=True),
    sa.Column('pentavalent_date', sa.DATE(), nullable=True),
    sa.Column('measles_date', sa.DATE(), nullable=True),
    sa.Column('growth_notes', sa.TEXT(), nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('households_visited', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('work_pending', sa.TEXT(), nullable=True),
    sa.Column('work_done', sa.TEXT(), nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_patient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=10), nullable=True),
    sa.Column('village', sa.VARCHAR(length=120), nullable=True),
    sa.Column('problem', sa.TEXT(), nullable=True),
    sa.Column('referral_facility', sa.VARCHAR(length=120), nullable=True),
    sa.Column('referral_date', sa.DATE(), nullable=True),
    sa.Column('follow_up_date', sa.DATE(), nullable=True),
    sa.Column('outcome', sa.TEXT(), nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elderly_person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=10), nullable=True),
    sa.Column('village', sa.VARCHAR(length=120), nullable=True),
    sa.Column('bp_sys', sa.INTEGER(), nullable=True),
    sa.Column('bp_dia', sa.INTEGER(), nullable=True),
    sa.Column('sugar_fasting', sa.FLOAT(), nullable=True),
    sa.Column('sugar_random', sa.FLOAT(), nullable=True),
    sa.Column('blood_sugar', sa.FLOAT(), nullable=True),
    sa.Column('illnesses', sa.TEXT(), nullable=True),
    sa.Column('medicines', sa.TEXT(), nullable=True),
    sa.Column('follow_up_date', sa.DATE(), nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('immunization')
    op.drop_table('anc_visit')
    op.drop_table('task')
    op.drop_table('pregnancy')
    op.drop_table('health_visit')
    op.drop_table('elderly_profile')
    op.drop_table('child_profile')
    op.drop_table('case_record')
    op.drop_table('person')
    op.drop_table('household')
    # ### end Alembic commands ###
