"""update TT doses

Revision ID: a44a8d08f8bf
Revises: abe4bea2230b
Create Date: 2026-02-13 20:30:02.416601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44a8d08f8bf'
down_revision = 'abe4bea2230b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anc_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tt_dose', sa.String(length=10), nullable=True))
        batch_op.drop_column('tt_given')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anc_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tt_given', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('tt_dose')

    # ### end Alembic commands ###
