"""add status and last_taken_date to medicine_reminder

Revision ID: aadfc7d9dce4
Revises: 7d15c5614a21
Create Date: 2026-02-04 00:59:59.051889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadfc7d9dce4'
down_revision = '7d15c5614a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_taken_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_reminder', schema=None) as batch_op:
        batch_op.drop_column('last_taken_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
