"""update elder table

Revision ID: abe4bea2230b
Revises: 88bd9a910c97
Create Date: 2026-02-13 19:40:20.426278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe4bea2230b'
down_revision = '88bd9a910c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bp', sa.String(length=20), nullable=True))
        batch_op.drop_column('bp_sys')
        batch_op.drop_column('bp_dia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bp_dia', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bp_sys', sa.INTEGER(), nullable=True))
        batch_op.drop_column('bp')

    # ### end Alembic commands ###
