"""update model

Revision ID: e9723f6e2078
Revises: 4d3c8dda8c30
Create Date: 2026-02-24 21:44:47.150536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9723f6e2078'
down_revision = '4d3c8dda8c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccine')
    with op.batch_alter_table('child_immunization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_immunization_child_id'))
        batch_op.drop_index(batch_op.f('ix_child_immunization_vaccine_schedule_id'))

    op.drop_table('child_immunization')
    with op.batch_alter_table('vaccine_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccine_schedule_vaccine_id'))

    op.drop_table('vaccine_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vaccine_id', sa.INTEGER(), nullable=False),
    sa.Column('dose_number', sa.INTEGER(), nullable=False),
    sa.Column('min_age_days', sa.INTEGER(), nullable=True),
    sa.Column('recommended_age_days', sa.INTEGER(), nullable=True),
    sa.Column('max_age_days', sa.INTEGER(), nullable=True),
    sa.Column('is_booster', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccine_id', 'dose_number', name='unique_vaccine_dose')
    )
    with op.batch_alter_table('vaccine_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccine_schedule_vaccine_id'), ['vaccine_id'], unique=False)

    op.create_table('child_immunization',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.Column('vaccine_schedule_id', sa.INTEGER(), nullable=False),
    sa.Column('date_given', sa.DATE(), nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('given_at', sa.VARCHAR(length=120), nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profile.id'], ),
    sa.ForeignKeyConstraint(['vaccine_schedule_id'], ['vaccine_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_immunization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_immunization_vaccine_schedule_id'), ['vaccine_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_immunization_child_id'), ['child_id'], unique=False)

    op.create_table('vaccine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
