"""update immunization

Revision ID: efdea1d48ce5
Revises: a44a8d08f8bf
Create Date: 2026-02-13 21:50:00.044077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdea1d48ce5'
down_revision = 'a44a8d08f8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vaccine_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('min_age_days', sa.Integer(), nullable=True),
    sa.Column('recommended_age_days', sa.Integer(), nullable=True),
    sa.Column('max_age_days', sa.Integer(), nullable=True),
    sa.Column('is_booster', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccine_id', 'dose_number', name='unique_vaccine_dose')
    )
    op.create_table('child_immunization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_schedule_id', sa.Integer(), nullable=False),
    sa.Column('date_given', sa.Date(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('given_at', sa.String(length=120), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profile.id'], ),
    sa.ForeignKeyConstraint(['vaccine_schedule_id'], ['vaccine_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('immunization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immunization',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=True),
    sa.Column('vaccine_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dose_number', sa.INTEGER(), nullable=True),
    sa.Column('date_given', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('child_immunization')
    op.drop_table('vaccine_schedule')
    op.drop_table('vaccine')
    # ### end Alembic commands ###
